# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/127ai7gWu1ricucmFhP10XQkrBKRfBuBf
"""

"""
Analise completa do dataset Olist - Tech Challenge
Gera todas as visualizacoes e metricas para o relatorio executivo.
"""

import os
import sys
import warnings

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
import pandas as pd
import numpy as np

warnings.filterwarnings("ignore")

# Configuracao visual profissional
sns.set_theme(style="whitegrid", font_scale=1.1)
PALETTE = ["#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", "#9467bd",
           "#8c564b", "#e377c2", "#7f7f7f", "#bcbd22", "#17becf"]
plt.rcParams.update({
    "figure.facecolor": "white",
    "axes.facecolor": "white",
    "savefig.dpi": 150,
    "savefig.bbox": "tight",
    "font.family": "sans-serif",
})

CHARTS_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "output", "charts")
os.makedirs(CHARTS_DIR, exist_ok=True)

sys.path.insert(0, os.path.dirname(__file__))
from data_loader import load_all_datasets, clean_and_prepare  # noqa: E402


def fmt_brl(value):
    """Formata valor em BRL."""
    return f"R$ {value:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")


def save_fig(fig, name):
    path = os.path.join(CHARTS_DIR, name)
    fig.savefig(path, dpi=150, bbox_inches="tight", facecolor="white")
    plt.close(fig)
    print(f"  Salvo: {name}")


# ===========================================================================
# 1. CRESCIMENTO E RECEITA
# ===========================================================================
def analise_crescimento_receita(data):
    print("\n=== 1. CRESCIMENTO E RECEITA ===")
    orders_full = data["orders_full"]

    # Filtrar apenas pedidos entregues/enviados com data valida
    delivered = orders_full[
        orders_full["order_status"].isin(["delivered", "shipped", "invoiced", "processing"])
    ].copy()
    delivered = delivered.dropna(subset=["order_purchase_timestamp"])
    delivered["year_month"] = delivered["order_purchase_timestamp"].dt.to_period("M")

    monthly = delivered.groupby("year_month").agg(
        pedidos=("order_id", "nunique"),
        receita=("total_order_value", "sum"),
        ticket_medio=("total_order_value", "mean"),
    ).reset_index()
    monthly["year_month_str"] = monthly["year_month"].astype(str)

    # --- Grafico 1.1: Evolucao mensal de pedidos e receita ---
    fig, ax1 = plt.subplots(figsize=(14, 6))
    color_pedidos = PALETTE[0]
    color_receita = PALETTE[1]

    ax1.bar(monthly["year_month_str"], monthly["pedidos"], color=color_pedidos, alpha=0.7, label="Pedidos")
    ax1.set_xlabel("Mes")
    ax1.set_ylabel("Numero de Pedidos", color=color_pedidos)
    ax1.tick_params(axis="y", labelcolor=color_pedidos)
    ax1.set_xticklabels(monthly["year_month_str"], rotation=45, ha="right")

    ax2 = ax1.twinx()
    ax2.plot(monthly["year_month_str"], monthly["receita"] / 1000, color=color_receita,
             marker="o", linewidth=2.5, markersize=6, label="Receita (R$ mil)")
    ax2.set_ylabel("Receita (R$ mil)", color=color_receita)
    ax2.tick_params(axis="y", labelcolor=color_receita)

    fig.suptitle("Evolucao Mensal de Pedidos e Receita", fontsize=16, fontweight="bold", y=1.02)
    lines1, labels1 = ax1.get_legend_handles_labels()
    lines2, labels2 = ax2.get_legend_handles_labels()
    ax1.legend(lines1 + lines2, labels1 + labels2, loc="upper left")
    fig.tight_layout()
    save_fig(fig, "1_1_evolucao_mensal_pedidos_receita.png")

    # --- Grafico 1.2: Ticket medio mensal ---
    fig, ax = plt.subplots(figsize=(14, 5))
    ax.plot(monthly["year_month_str"], monthly["ticket_medio"], color=PALETTE[2],
            marker="s", linewidth=2.5, markersize=6)
    ax.fill_between(range(len(monthly)), monthly["ticket_medio"], alpha=0.15, color=PALETTE[2])
    ax.set_xticklabels(monthly["year_month_str"], rotation=45, ha="right")
    ax.set_xlabel("Mes")
    ax.set_ylabel("Ticket Medio (R$)")
    ax.set_title("Evolucao do Ticket Medio Mensal", fontsize=14, fontweight="bold")
    ax.yaxis.set_major_formatter(mticker.FormatStrFormatter("R$ %.0f"))
    fig.tight_layout()
    save_fig(fig, "1_2_ticket_medio_mensal.png")

    # --- Grafico 1.3: Top 10 categorias por receita ---
    main = data["main"].copy()
    main_delivered = main[main["order_status"].isin(["delivered", "shipped", "invoiced", "processing"])]
    cat_revenue = main_delivered.groupby("category")["price"].sum().sort_values(ascending=False).head(10)

    fig, ax = plt.subplots(figsize=(12, 6))
    bars = ax.barh(cat_revenue.index[::-1], cat_revenue.values[::-1] / 1000, color=PALETTE[0], edgecolor="white")
    ax.set_xlabel("Receita (R$ mil)")
    ax.set_title("Top 10 Categorias por Receita", fontsize=14, fontweight="bold")
    for bar in bars:
        width = bar.get_width()
        ax.text(width + 5, bar.get_y() + bar.get_height() / 2,
                f"R$ {width:,.0f}k", va="center", fontsize=9)
    fig.tight_layout()
    save_fig(fig, "1_3_top10_categorias_receita.png")

    # --- Grafico 1.4: Participacao por estado (top 10) ---
    state_revenue = main_delivered.groupby("customer_state")["price"].sum().sort_values(ascending=False).head(10)

    fig, ax = plt.subplots(figsize=(10, 6))
    colors_state = sns.color_palette("Blues_r", len(state_revenue))
    ax.bar(state_revenue.index, state_revenue.values / 1000, color=colors_state, edgecolor="white")
    ax.set_xlabel("Estado")
    ax.set_ylabel("Receita (R$ mil)")
    ax.set_title("Top 10 Estados por Receita", fontsize=14, fontweight="bold")
    for i, (idx, val) in enumerate(state_revenue.items()):
        ax.text(i, val / 1000 + 10, f"{val / state_revenue.sum() * 100:.1f}%",
                ha="center", fontsize=9, fontweight="bold")
    fig.tight_layout()
    save_fig(fig, "1_4_top10_estados_receita.png")

    # --- Grafico 1.5: Top 10 sellers por receita ---
    seller_rev = main_delivered.groupby("seller_id").agg(
        receita=("price", "sum"),
        pedidos=("order_id", "nunique"),
        cidade=("seller_city", "first"),
        estado=("seller_state", "first"),
    ).sort_values("receita", ascending=False).head(10)

    fig, ax = plt.subplots(figsize=(12, 6))
    labels = [f"{row.cidade[:15]}-{row.estado}" for _, row in seller_rev.iterrows()]
    ax.barh(labels[::-1], seller_rev["receita"].values[::-1] / 1000, color=PALETTE[1], edgecolor="white")
    ax.set_xlabel("Receita (R$ mil)")
    ax.set_title("Top 10 Sellers por Receita", fontsize=14, fontweight="bold")
    fig.tight_layout()
    save_fig(fig, "1_5_top10_sellers_receita.png")

    # Metricas resumo
    total_receita = delivered["total_order_value"].sum()
    total_pedidos = delivered["order_id"].nunique()
    ticket_medio_geral = delivered["total_order_value"].mean()
    crescimento = ((monthly["pedidos"].iloc[-2] - monthly["pedidos"].iloc[2]) /
                   monthly["pedidos"].iloc[2] * 100) if len(monthly) > 3 else 0

    metricas = {
        "receita_total": total_receita,
        "total_pedidos": total_pedidos,
        "ticket_medio": ticket_medio_geral,
        "crescimento_pedidos_pct": crescimento,
        "top_categoria": cat_revenue.index[0],
        "top_estado": state_revenue.index[0],
        "monthly": monthly,
    }
    print(f"  Receita total: {fmt_brl(total_receita)}")
    print(f"  Total pedidos: {total_pedidos:,}")
    print(f"  Ticket medio: {fmt_brl(ticket_medio_geral)}")
    return metricas


# ===========================================================================
# 2. LOGISTICA E SLA
# ===========================================================================
def analise_logistica_sla(data):
    print("\n=== 2. LOGISTICA E SLA ===")
    orders = data["orders_full"].copy()
    delivered = orders[orders["order_status"] == "delivered"].dropna(subset=["lead_time_total"])

    # --- Grafico 2.1: Distribuicao do lead time total ---
    fig, ax = plt.subplots(figsize=(12, 5))
    lead_times = delivered["lead_time_total"].clip(0, 60)
    ax.hist(lead_times, bins=60, color=PALETTE[0], alpha=0.8, edgecolor="white")
    median_lt = delivered["lead_time_total"].median()
    ax.axvline(median_lt, color=PALETTE[3], linestyle="--", linewidth=2,
               label=f"Mediana: {median_lt:.1f} dias")
    ax.set_xlabel("Dias ate Entrega")
    ax.set_ylabel("Numero de Pedidos")
    ax.set_title("Distribuicao do Tempo Total de Entrega", fontsize=14, fontweight="bold")
    ax.legend(fontsize=12)
    fig.tight_layout()
    save_fig(fig, "2_1_distribuicao_lead_time.png")

    # --- Grafico 2.2: Lead time por etapa (boxplot) ---
    etapas = delivered[["lead_time_approval", "lead_time_carrier", "lead_time_delivery"]].copy()
    etapas.columns = ["Aprovacao (h)", "Postagem (dias)", "Transporte (dias)"]
    etapas["Aprovacao (h)"] = etapas["Aprovacao (h)"].clip(0, 72)
    etapas["Postagem (dias)"] = etapas["Postagem (dias)"].clip(0, 15)
    etapas["Transporte (dias)"] = etapas["Transporte (dias)"].clip(0, 40)

    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    for i, col in enumerate(etapas.columns):
        sns.boxplot(y=etapas[col], ax=axes[i], color=PALETTE[i], width=0.5)
        axes[i].set_title(col, fontsize=12, fontweight="bold")
    fig.suptitle("Tempo por Etapa do Processo", fontsize=14, fontweight="bold", y=1.02)
    fig.tight_layout()
    save_fig(fig, "2_2_lead_time_por_etapa.png")

    # --- Grafico 2.3: Atrasos vs review_score ---
    delivered_with_review = delivered.dropna(subset=["review_score", "delivery_vs_estimate"])
    delivered_with_review["status_entrega"] = delivered_with_review["delivery_vs_estimate"].apply(
        lambda x: "Atrasado" if x > 0 else "No prazo/Adiantado"
    )

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    # Score medio por status de entrega
    score_by_status = delivered_with_review.groupby("status_entrega")["review_score"].mean()
    colors_status = [PALETTE[3] if s == "Atrasado" else PALETTE[2] for s in score_by_status.index]
    axes[0].bar(score_by_status.index, score_by_status.values, color=colors_status, edgecolor="white")
    axes[0].set_ylabel("Review Score Medio")
    axes[0].set_title("Score Medio: Atrasados vs No Prazo", fontsize=12, fontweight="bold")
    axes[0].set_ylim(0, 5.5)
    for i, (idx, val) in enumerate(score_by_status.items()):
        axes[0].text(i, val + 0.1, f"{val:.2f}", ha="center", fontsize=12, fontweight="bold")

    # Distribuicao de scores para atrasados vs no prazo
    for status, color in [("No prazo/Adiantado", PALETTE[2]), ("Atrasado", PALETTE[3])]:
        subset = delivered_with_review[delivered_with_review["status_entrega"] == status]
        score_dist = subset["review_score"].value_counts(normalize=True).sort_index()
        axes[1].bar(score_dist.index + (-0.2 if status == "No prazo/Adiantado" else 0.2),
                    score_dist.values * 100, width=0.35, color=color, alpha=0.8,
                    label=status, edgecolor="white")
    axes[1].set_xlabel("Review Score")
    axes[1].set_ylabel("% dos Pedidos")
    axes[1].set_title("Distribuicao de Scores por Status de Entrega", fontsize=12, fontweight="bold")
    axes[1].legend()
    axes[1].set_xticks([1, 2, 3, 4, 5])
    fig.tight_layout()
    save_fig(fig, "2_3_atrasos_vs_review_score.png")

    # --- Grafico 2.4: Taxa de atraso por estado ---
    state_delivery = delivered.dropna(subset=["is_late"]).groupby("customer_state").agg(
        total=("order_id", "count"),
        atrasados=("is_late", "sum"),
    )
    state_delivery["taxa_atraso"] = state_delivery["atrasados"] / state_delivery["total"] * 100
    state_delivery = state_delivery[state_delivery["total"] >= 50].sort_values("taxa_atraso", ascending=False).head(15)

    fig, ax = plt.subplots(figsize=(12, 6))
    colors_delay = [PALETTE[3] if v > 10 else PALETTE[0] for v in state_delivery["taxa_atraso"]]
    ax.bar(state_delivery.index, state_delivery["taxa_atraso"], color=colors_delay, edgecolor="white")
    ax.set_xlabel("Estado")
    ax.set_ylabel("Taxa de Atraso (%)")
    ax.set_title("Taxa de Atraso na Entrega por Estado", fontsize=14, fontweight="bold")
    ax.axhline(y=state_delivery["taxa_atraso"].mean(), color="gray", linestyle="--", alpha=0.7,
               label=f"Media: {state_delivery['taxa_atraso'].mean():.1f}%")
    ax.legend()
    fig.tight_layout()
    save_fig(fig, "2_4_taxa_atraso_por_estado.png")

    # --- Grafico 2.5: Lead time medio mensal ---
    delivered["year_month"] = delivered["order_purchase_timestamp"].dt.to_period("M")
    monthly_lt = delivered.groupby("year_month")["lead_time_total"].median().reset_index()
    monthly_lt["year_month_str"] = monthly_lt["year_month"].astype(str)

    fig, ax = plt.subplots(figsize=(14, 5))
    ax.plot(monthly_lt["year_month_str"], monthly_lt["lead_time_total"],
            color=PALETTE[0], marker="o", linewidth=2.5, markersize=6)
    ax.fill_between(range(len(monthly_lt)), monthly_lt["lead_time_total"],
                    alpha=0.15, color=PALETTE[0])
    ax.set_xticklabels(monthly_lt["year_month_str"], rotation=45, ha="right")
    ax.set_xlabel("Mes")
    ax.set_ylabel("Mediana Lead Time (dias)")
    ax.set_title("Evolucao Mensal do Tempo Mediano de Entrega", fontsize=14, fontweight="bold")
    fig.tight_layout()
    save_fig(fig, "2_5_lead_time_mensal.png")

    pct_atraso = delivered["is_late"].mean() * 100
    metricas = {
        "mediana_lead_time": median_lt,
        "pct_atraso": pct_atraso,
        "score_no_prazo": score_by_status.get("No prazo/Adiantado", 0),
        "score_atrasado": score_by_status.get("Atrasado", 0),
    }
    print(f"  Mediana lead time: {median_lt:.1f} dias")
    print(f"  Taxa de atraso: {pct_atraso:.1f}%")
    return metricas


# ===========================================================================
# 3. COMPORTAMENTO E PAGAMENTOS
# ===========================================================================
def analise_pagamentos(data):
    print("\n=== 3. COMPORTAMENTO E PAGAMENTOS ===")
    payments = data["payments"].copy()
    orders_full = data["orders_full"].copy()

    # --- Grafico 3.1: Meios de pagamento ---
    pay_type = payments.groupby("payment_type").agg(
        total_valor=("payment_value", "sum"),
        total_transacoes=("payment_type", "count"),
    ).sort_values("total_transacoes", ascending=False)

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    labels_pt = {
        "credit_card": "Cartao Credito",
        "boleto": "Boleto",
        "voucher": "Voucher",
        "debit_card": "Cartao Debito",
        "not_defined": "Nao definido",
    }
    labels = [labels_pt.get(x, x) for x in pay_type.index]
    colors_pay = PALETTE[:len(pay_type)]

    axes[0].pie(pay_type["total_transacoes"], labels=labels, autopct="%1.1f%%",
                colors=colors_pay, startangle=90, textprops={"fontsize": 10})
    axes[0].set_title("Transacoes por Meio de Pagamento", fontsize=12, fontweight="bold")

    axes[1].pie(pay_type["total_valor"], labels=labels, autopct="%1.1f%%",
                colors=colors_pay, startangle=90, textprops={"fontsize": 10})
    axes[1].set_title("Volume Financeiro por Meio de Pagamento", fontsize=12, fontweight="bold")
    fig.tight_layout()
    save_fig(fig, "3_1_meios_pagamento.png")

    # --- Grafico 3.2: Distribuicao de parcelas ---
    credit = payments[payments["payment_type"] == "credit_card"].copy()
    installments_dist = credit.groupby("payment_installments").agg(
        count=("payment_value", "count"),
        avg_value=("payment_value", "mean"),
    ).reset_index()
    installments_dist = installments_dist[installments_dist["payment_installments"] <= 12]

    fig, ax1 = plt.subplots(figsize=(12, 5))
    ax1.bar(installments_dist["payment_installments"], installments_dist["count"],
            color=PALETTE[0], alpha=0.7, label="Qtd Transacoes")
    ax1.set_xlabel("Numero de Parcelas")
    ax1.set_ylabel("Quantidade de Transacoes", color=PALETTE[0])
    ax1.tick_params(axis="y", labelcolor=PALETTE[0])

    ax2 = ax1.twinx()
    ax2.plot(installments_dist["payment_installments"], installments_dist["avg_value"],
             color=PALETTE[1], marker="o", linewidth=2.5, label="Valor Medio (R$)")
    ax2.set_ylabel("Valor Medio da Compra (R$)", color=PALETTE[1])
    ax2.tick_params(axis="y", labelcolor=PALETTE[1])

    fig.suptitle("Distribuicao de Parcelas no Cartao de Credito", fontsize=14, fontweight="bold", y=1.02)
    lines1, labels1 = ax1.get_legend_handles_labels()
    lines2, labels2 = ax2.get_legend_handles_labels()
    ax1.legend(lines1 + lines2, labels1 + labels2, loc="upper right")
    ax1.set_xticks(range(1, 13))
    fig.tight_layout()
    save_fig(fig, "3_2_distribuicao_parcelas.png")

    # --- Grafico 3.3: Analise RFM ---
    delivered = orders_full[orders_full["order_status"] == "delivered"].dropna(
        subset=["order_purchase_timestamp", "total_order_value"]
    ).copy()
    reference_date = delivered["order_purchase_timestamp"].max() + pd.Timedelta(days=1)

    rfm = delivered.groupby("customer_unique_id").agg(
        recency=("order_purchase_timestamp", lambda x: (reference_date - x.max()).days),
        frequency=("order_id", "nunique"),
        monetary=("total_order_value", "sum"),
    ).reset_index()

    # Segmentacao RFM simplificada
    rfm["R_score"] = pd.qcut(rfm["recency"], 4, labels=[4, 3, 2, 1])
    rfm["F_score"] = pd.cut(rfm["frequency"], bins=[0, 1, 2, 3, 100], labels=[1, 2, 3, 4])
    rfm["M_score"] = pd.qcut(rfm["monetary"], 4, labels=[1, 2, 3, 4])
    rfm["RFM_score"] = rfm[["R_score", "F_score", "M_score"]].astype(int).sum(axis=1)

    def rfm_segment(score):
        if score >= 10:
            return "Champions"
        elif score >= 8:
            return "Loyal"
        elif score >= 6:
            return "Potential"
        elif score >= 4:
            return "At Risk"
        else:
            return "Lost"

    rfm["segment"] = rfm["RFM_score"].apply(rfm_segment)

    segment_summary = rfm.groupby("segment").agg(
        clientes=("customer_unique_id", "count"),
        receita_media=("monetary", "mean"),
        recencia_media=("recency", "mean"),
    ).sort_values("clientes", ascending=False)

    fig, axes = plt.subplots(1, 2, figsize=(14, 6))
    seg_colors = {"Champions": PALETTE[2], "Loyal": PALETTE[0], "Potential": PALETTE[1],
                  "At Risk": PALETTE[4], "Lost": PALETTE[3]}
    colors_seg = [seg_colors.get(s, "gray") for s in segment_summary.index]

    axes[0].pie(segment_summary["clientes"], labels=segment_summary.index, autopct="%1.1f%%",
                colors=colors_seg, startangle=90, textprops={"fontsize": 10})
    axes[0].set_title("Distribuicao de Clientes por Segmento RFM", fontsize=12, fontweight="bold")

    axes[1].barh(segment_summary.index[::-1], segment_summary["receita_media"].values[::-1],
                 color=[seg_colors.get(s, "gray") for s in segment_summary.index[::-1]], edgecolor="white")
    axes[1].set_xlabel("Receita Media por Cliente (R$)")
    axes[1].set_title("Receita Media por Segmento RFM", fontsize=12, fontweight="bold")
    fig.tight_layout()
    save_fig(fig, "3_3_analise_rfm.png")

    # --- Grafico 3.4: Taxa de recompra ---
    customer_orders = delivered.groupby("customer_unique_id")["order_id"].nunique()
    recompra = (customer_orders > 1).sum()
    total_customers = len(customer_orders)
    taxa_recompra = recompra / total_customers * 100

    fig, ax = plt.subplots(figsize=(8, 6))
    sizes = [total_customers - recompra, recompra]
    labels_rec = [f"Compra unica\n({total_customers - recompra:,})", f"Recompra\n({recompra:,})"]
    colors_rec = [PALETTE[0], PALETTE[2]]
    wedges, texts, autotexts = ax.pie(sizes, labels=labels_rec, autopct="%1.1f%%",
                                       colors=colors_rec, startangle=90, textprops={"fontsize": 11})
    ax.set_title(f"Taxa de Recompra: {taxa_recompra:.1f}%", fontsize=14, fontweight="bold")
    fig.tight_layout()
    save_fig(fig, "3_4_taxa_recompra.png")

    metricas = {
        "pct_cartao_credito": pay_type.loc["credit_card", "total_transacoes"] / pay_type["total_transacoes"].sum() * 100
        if "credit_card" in pay_type.index else 0,
        "taxa_recompra": taxa_recompra,
        "total_clientes_unicos": total_customers,
        "rfm_segments": segment_summary,
    }
    print(f"  Cartao de credito: {metricas['pct_cartao_credito']:.1f}% das transacoes")
    print(f"  Taxa de recompra: {taxa_recompra:.1f}%")
    print(f"  Clientes unicos: {total_customers:,}")
    return metricas


# ===========================================================================
# 4. SATISFACAO DO CLIENTE
# ===========================================================================
def analise_satisfacao(data):
    print("\n=== 4. SATISFACAO DO CLIENTE ===")
    orders_full = data["orders_full"].copy()
    delivered = orders_full[orders_full["order_status"] == "delivered"].dropna(subset=["review_score"])

    # --- Grafico 4.1: Distribuicao de review scores ---
    score_dist = delivered["review_score"].value_counts().sort_index()
    total = score_dist.sum()

    fig, ax = plt.subplots(figsize=(10, 6))
    colors_score = [PALETTE[3], PALETTE[3], PALETTE[1], PALETTE[2], PALETTE[2]]
    bars = ax.bar(score_dist.index, score_dist.values, color=colors_score, edgecolor="white", width=0.7)
    ax.set_xlabel("Review Score")
    ax.set_ylabel("Numero de Pedidos")
    ax.set_title("Distribuicao das Avaliacoes dos Clientes", fontsize=14, fontweight="bold")
    ax.set_xticks([1, 2, 3, 4, 5])
    for bar, val in zip(bars, score_dist.values):
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 200,
                f"{val:,}\n({val / total * 100:.1f}%)", ha="center", fontsize=10)
    fig.tight_layout()
    save_fig(fig, "4_1_distribuicao_reviews.png")

    # --- Grafico 4.2: Score medio por categoria (top 15) ---
    main = data["main"].copy()
    main_del = main[main["order_status"] == "delivered"].dropna(subset=["review_score", "category"])
    cat_score = main_del.groupby("category").agg(
        score_medio=("review_score", "mean"),
        count=("order_id", "count"),
    )
    cat_score = cat_score[cat_score["count"] >= 100].sort_values("score_medio", ascending=True).tail(15)

    fig, ax = plt.subplots(figsize=(12, 7))
    colors_cat = [PALETTE[2] if s >= 4 else PALETTE[1] if s >= 3.5 else PALETTE[3] for s in cat_score["score_medio"]]
    ax.barh(cat_score.index, cat_score["score_medio"], color=colors_cat, edgecolor="white")
    ax.set_xlabel("Score Medio")
    ax.set_xlim(2.5, 5)
    ax.set_title("Score Medio por Categoria (min. 100 pedidos)", fontsize=14, fontweight="bold")
    ax.axvline(x=4.0, color="gray", linestyle="--", alpha=0.5)
    for i, (idx, row) in enumerate(cat_score.iterrows()):
        ax.text(row["score_medio"] + 0.03, i, f"{row['score_medio']:.2f}", va="center", fontsize=9)
    fig.tight_layout()
    save_fig(fig, "4_2_score_por_categoria.png")

    # --- Grafico 4.3: Drivers de satisfacao ---
    drivers = delivered.dropna(subset=["lead_time_total", "total_order_value"]).copy()
    drivers["faixa_lead_time"] = pd.cut(drivers["lead_time_total"],
                                         bins=[0, 5, 10, 15, 20, 30, 100],
                                         labels=["0-5d", "5-10d", "10-15d", "15-20d", "20-30d", "30d+"])
    drivers["faixa_preco"] = pd.cut(drivers["total_order_value"],
                                     bins=[0, 50, 100, 200, 500, 10000],
                                     labels=["<R$50", "R$50-100", "R$100-200", "R$200-500", "R$500+"])

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    lt_score = drivers.groupby("faixa_lead_time")["review_score"].mean()
    axes[0].bar(lt_score.index.astype(str), lt_score.values, color=PALETTE[0], edgecolor="white")
    axes[0].set_xlabel("Tempo de Entrega")
    axes[0].set_ylabel("Score Medio")
    axes[0].set_title("Score por Tempo de Entrega", fontsize=12, fontweight="bold")
    axes[0].set_ylim(2, 5)

    price_score = drivers.groupby("faixa_preco")["review_score"].mean()
    axes[1].bar(price_score.index.astype(str), price_score.values, color=PALETTE[1], edgecolor="white")
    axes[1].set_xlabel("Faixa de Preco")
    axes[1].set_ylabel("Score Medio")
    axes[1].set_title("Score por Faixa de Preco", fontsize=12, fontweight="bold")
    axes[1].set_ylim(2, 5)
    fig.tight_layout()
    save_fig(fig, "4_3_drivers_satisfacao.png")

    # --- Grafico 4.4: Evolucao mensal do NPS ---
    delivered["year_month"] = delivered["order_purchase_timestamp"].dt.to_period("M")
    monthly_nps = delivered.groupby("year_month").apply(
        lambda x: ((x["review_score"] >= 4).sum() - (x["review_score"] <= 2).sum()) / len(x) * 100
    ).reset_index(name="nps")
    monthly_nps["year_month_str"] = monthly_nps["year_month"].astype(str)

    fig, ax = plt.subplots(figsize=(14, 5))
    colors_nps = [PALETTE[2] if n >= 50 else PALETTE[1] if n >= 30 else PALETTE[3] for n in monthly_nps["nps"]]
    ax.bar(monthly_nps["year_month_str"], monthly_nps["nps"], color=colors_nps, edgecolor="white")
    ax.set_xticklabels(monthly_nps["year_month_str"], rotation=45, ha="right")
    ax.set_xlabel("Mes")
    ax.set_ylabel("NPS (%)")
    ax.set_title("Evolucao Mensal do NPS (Net Promoter Score)", fontsize=14, fontweight="bold")
    ax.axhline(y=50, color="gray", linestyle="--", alpha=0.5, label="Zona de excelencia (50+)")
    ax.legend()
    fig.tight_layout()
    save_fig(fig, "4_4_evolucao_nps.png")

    score_medio = delivered["review_score"].mean()
    pct_5_estrelas = (delivered["review_score"] == 5).mean() * 100
    pct_1_estrela = (delivered["review_score"] == 1).mean() * 100
    nps_geral = ((delivered["review_score"] >= 4).sum() - (delivered["review_score"] <= 2).sum()) / len(delivered) * 100

    metricas = {
        "score_medio": score_medio,
        "pct_5_estrelas": pct_5_estrelas,
        "pct_1_estrela": pct_1_estrela,
        "nps_geral": nps_geral,
    }
    print(f"  Score medio: {score_medio:.2f}")
    print(f"  5 estrelas: {pct_5_estrelas:.1f}%")
    print(f"  NPS geral: {nps_geral:.1f}")
    return metricas


# ===========================================================================
# 5. OPORTUNIDADES E RECOMENDACOES
# ===========================================================================
def analise_oportunidades(data):
    print("\n=== 5. OPORTUNIDADES E RECOMENDACOES ===")
    main = data["main"].copy()
    orders_full = data["orders_full"].copy()

    main_del = main[main["order_status"] == "delivered"].copy()

    # --- Grafico 5.1: Frete como % do preco por categoria ---
    cat_freight = main_del.groupby("category").agg(
        preco_medio=("price", "mean"),
        frete_medio=("freight_value", "mean"),
        count=("order_id", "count"),
    )
    cat_freight["frete_pct"] = cat_freight["frete_medio"] / cat_freight["preco_medio"] * 100
    cat_freight = cat_freight[cat_freight["count"] >= 100].sort_values("frete_pct", ascending=False).head(15)

    fig, ax = plt.subplots(figsize=(12, 7))
    colors_freight = [PALETTE[3] if f > 30 else PALETTE[1] if f > 20 else PALETTE[2]
                      for f in cat_freight["frete_pct"]]
    ax.barh(cat_freight.index[::-1], cat_freight["frete_pct"].values[::-1],
            color=colors_freight[::-1], edgecolor="white")
    ax.set_xlabel("Frete como % do Preco do Produto")
    ax.set_title("Categorias com Maior Peso de Frete", fontsize=14, fontweight="bold")
    ax.axvline(x=20, color="gray", linestyle="--", alpha=0.5, label="Limite 20%")
    ax.legend()
    fig.tight_layout()
    save_fig(fig, "5_1_frete_pct_por_categoria.png")

    # --- Grafico 5.2: Sellers - Score vs Lead Time ---
    seller_perf = main_del.dropna(subset=["review_score", "lead_time_total"]).groupby("seller_id").agg(
        score_medio=("review_score", "mean"),
        lead_time_medio=("lead_time_total", "mean"),
        receita=("price", "sum"),
        pedidos=("order_id", "nunique"),
    ).reset_index()
    seller_perf = seller_perf[seller_perf["pedidos"] >= 10]

    fig, ax = plt.subplots(figsize=(12, 7))
    scatter = ax.scatter(seller_perf["lead_time_medio"], seller_perf["score_medio"],
                         s=seller_perf["receita"] / 100, alpha=0.5, c=seller_perf["score_medio"],
                         cmap="RdYlGn", edgecolors="white", linewidth=0.5)
    ax.set_xlabel("Lead Time Medio (dias)")
    ax.set_ylabel("Score Medio")
    ax.set_title("Performance dos Sellers: Score vs Lead Time\n(tamanho = receita)", fontsize=14, fontweight="bold")
    ax.axhline(y=4, color="gray", linestyle="--", alpha=0.5)
    ax.axvline(x=15, color="gray", linestyle="--", alpha=0.5)
    ax.text(5, 4.8, "IDEAL\n(rapido + bem avaliado)", fontsize=9, color=PALETTE[2], fontweight="bold")
    ax.text(25, 2.5, "CRITICO\n(lento + mal avaliado)", fontsize=9, color=PALETTE[3], fontweight="bold")
    plt.colorbar(scatter, ax=ax, label="Score Medio")
    fig.tight_layout()
    save_fig(fig, "5_2_sellers_score_vs_leadtime.png")

    # --- Grafico 5.3: Oportunidade de cross-sell por categoria ---
    # Categorias mais compradas juntas
    order_cats = main_del.groupby("order_id")["category"].apply(list).reset_index()
    multi_cat = order_cats[order_cats["category"].apply(len) > 1]

    from itertools import combinations
    pairs = {}
    for cats in multi_cat["category"]:
        unique_cats = [c for c in set(cats) if isinstance(c, str)]
        if len(unique_cats) > 1:
            for pair in combinations(sorted(unique_cats), 2):
                pairs[pair] = pairs.get(pair, 0) + 1

    if pairs:
        top_pairs = sorted(pairs.items(), key=lambda x: x[1], reverse=True)[:10]
        top_pairs = [(p, c) for p, c in top_pairs if isinstance(p[0], str) and isinstance(p[1], str)]
        pair_labels = [f"{p[0][:20]} +\n{p[1][:20]}" for p, _ in top_pairs]
        pair_counts = [c for _, c in top_pairs]

        fig, ax = plt.subplots(figsize=(14, 6))
        ax.barh(pair_labels[::-1], pair_counts[::-1], color=PALETTE[4], edgecolor="white")
        ax.set_xlabel("Numero de Pedidos Conjuntos")
        ax.set_title("Top 10 Combinacoes de Categorias (Cross-Sell)", fontsize=14, fontweight="bold")
        fig.tight_layout()
        save_fig(fig, "5_3_crosssell_categorias.png")

    # --- Grafico 5.4: Mapa de calor receita por estado x categoria ---
    top_states = main_del.groupby("customer_state")["price"].sum().sort_values(ascending=False).head(8).index
    top_cats = main_del.groupby("category")["price"].sum().sort_values(ascending=False).head(8).index
    heatmap_data = main_del[
        main_del["customer_state"].isin(top_states) & main_del["category"].isin(top_cats)
    ].pivot_table(values="price", index="category", columns="customer_state", aggfunc="sum", fill_value=0)
    heatmap_data = heatmap_data / 1000  # em R$ mil

    fig, ax = plt.subplots(figsize=(12, 7))
    sns.heatmap(heatmap_data, annot=True, fmt=".0f", cmap="YlOrRd", ax=ax,
                cbar_kws={"label": "Receita (R$ mil)"}, linewidths=0.5)
    ax.set_title("Receita por Estado x Categoria (R$ mil)", fontsize=14, fontweight="bold")
    ax.set_xlabel("Estado")
    ax.set_ylabel("Categoria")
    fig.tight_layout()
    save_fig(fig, "5_4_heatmap_estado_categoria.png")

    # --- Grafico 5.5: Previsao de crescimento (tendencia linear) ---
    delivered = orders_full[
        orders_full["order_status"].isin(["delivered", "shipped", "invoiced", "processing"])
    ].dropna(subset=["order_purchase_timestamp"]).copy()
    delivered["year_month"] = delivered["order_purchase_timestamp"].dt.to_period("M")
    monthly = delivered.groupby("year_month").agg(receita=("total_order_value", "sum")).reset_index()
    monthly["month_num"] = range(len(monthly))

    # Tendencia linear
    valid = monthly.dropna(subset=["receita"])
    if len(valid) > 3:
        coeffs = np.polyfit(valid["month_num"], valid["receita"], 1)
        trend = np.poly1d(coeffs)

        # Projecao 6 meses
        future_months = list(range(len(monthly), len(monthly) + 6))
        future_values = trend(future_months)
        all_months = list(monthly["year_month"].astype(str))

        last_period = monthly["year_month"].iloc[-1]
        for i in range(1, 7):
            next_period = last_period + i
            all_months.append(str(next_period))

        fig, ax = plt.subplots(figsize=(14, 6))
        ax.bar(range(len(monthly)), monthly["receita"] / 1000, color=PALETTE[0], alpha=0.7, label="Realizado")
        ax.bar(future_months, future_values / 1000, color=PALETTE[1], alpha=0.5, label="Projecao (Tendencia)")
        ax.plot(range(len(monthly) + 6), trend(range(len(monthly) + 6)) / 1000,
                color=PALETTE[3], linestyle="--", linewidth=2, label="Linha de Tendencia")
        ax.set_xticks(range(0, len(all_months), 2))
        ax.set_xticklabels([all_months[i] for i in range(0, len(all_months), 2)], rotation=45, ha="right")
        ax.set_xlabel("Mes")
        ax.set_ylabel("Receita (R$ mil)")
        ax.set_title("Receita Realizada e Projecao de Tendencia", fontsize=14, fontweight="bold")
        ax.legend()
        fig.tight_layout()
        save_fig(fig, "5_5_projecao_receita.png")

    # Sellers ideais
    ideal_sellers = seller_perf[(seller_perf["score_medio"] >= 4) & (seller_perf["lead_time_medio"] <= 15)]
    pct_ideal = len(ideal_sellers) / len(seller_perf) * 100

    metricas = {
        "pct_sellers_ideais": pct_ideal,
        "total_sellers_avaliados": len(seller_perf),
        "categorias_alto_frete": list(cat_freight.head(5).index),
    }
    print(f"  Sellers ideais (score>=4, LT<=15d): {pct_ideal:.1f}%")
    return metricas


# ===========================================================================
# MAIN
# ===========================================================================
def main():
    print("=" * 60)
    print("TECH CHALLENGE - ANALISE OLIST E-COMMERCE")
    print("=" * 60)

    print("\nCarregando datasets...")
    dfs = load_all_datasets()

    print("\nLimpando e preparando dados...")
    data = clean_and_prepare(dfs)
    print(f"  Dataset principal: {data['main'].shape[0]:,} linhas")
    print(f"  Orders completo: {data['orders_full'].shape[0]:,} pedidos")

    m1 = analise_crescimento_receita(data)
    m2 = analise_logistica_sla(data)
    m3 = analise_pagamentos(data)
    m4 = analise_satisfacao(data)
    m5 = analise_oportunidades(data)

    print("\n" + "=" * 60)
    print("RESUMO EXECUTIVO - KPIs PRINCIPAIS")
    print("=" * 60)
    print(f"  Receita Total: {fmt_brl(m1['receita_total'])}")
    print(f"  Total de Pedidos: {m1['total_pedidos']:,}")
    print(f"  Ticket Medio: {fmt_brl(m1['ticket_medio'])}")
    print(f"  Mediana Lead Time: {m2['mediana_lead_time']:.1f} dias")
    print(f"  Taxa de Atraso: {m2['pct_atraso']:.1f}%")
    print(f"  Score Medio: {m4['score_medio']:.2f}")
    print(f"  NPS Geral: {m4['nps_geral']:.1f}")
    print(f"  Taxa de Recompra: {m3['taxa_recompra']:.1f}%")
    print(f"  Clientes Unicos: {m3['total_clientes_unicos']:,}")

    return {"m1": m1, "m2": m2, "m3": m3, "m4": m4, "m5": m5}


if __name__ == "__main__":
    results = main()