# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/127ai7gWu1ricucmFhP10XQkrBKRfBuBf
"""

"""
Modulo de carregamento e limpeza dos dados do Olist.
"""

import os
import pandas as pd

DATA_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data")


def load_all_datasets():
    """Carrega todos os CSVs do dataset Olist e retorna um dicionario de DataFrames."""
    files = {
        "customers": "olist_customers_dataset.csv",
        "orders": "olist_orders_dataset.csv",
        "order_items": "olist_order_items_dataset.csv",
        "payments": "olist_order_payments_dataset.csv",
        "reviews": "olist_order_reviews_dataset.csv",
        "products": "olist_products_dataset.csv",
        "sellers": "olist_sellers_dataset.csv",
        "geolocation": "olist_geolocation_dataset.csv",
        "category_translation": "product_category_name_translation.csv",
    }
    dfs = {}
    for name, filename in files.items():
        path = os.path.join(DATA_DIR, filename)
        dfs[name] = pd.read_csv(path)
        print(f"  {name}: {dfs[name].shape[0]:,} linhas x {dfs[name].shape[1]} colunas")
    return dfs


def clean_and_prepare(dfs):
    """Limpa e prepara os dados para analise."""

    orders = dfs["orders"].copy()
    date_cols = [
        "order_purchase_timestamp",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date",
        "order_estimated_delivery_date",
    ]
    for col in date_cols:
        orders[col] = pd.to_datetime(orders[col], errors="coerce")

    orders["order_year_month"] = orders["order_purchase_timestamp"].dt.to_period("M")
    orders["order_year"] = orders["order_purchase_timestamp"].dt.year
    orders["order_month"] = orders["order_purchase_timestamp"].dt.month
    orders["order_weekday"] = orders["order_purchase_timestamp"].dt.day_name()

    # Lead times em dias
    orders["lead_time_approval"] = (
        orders["order_approved_at"] - orders["order_purchase_timestamp"]
    ).dt.total_seconds() / 3600  # horas
    orders["lead_time_carrier"] = (
        orders["order_delivered_carrier_date"] - orders["order_approved_at"]
    ).dt.total_seconds() / 86400  # dias
    orders["lead_time_delivery"] = (
        orders["order_delivered_customer_date"] - orders["order_delivered_carrier_date"]
    ).dt.total_seconds() / 86400  # dias
    orders["lead_time_total"] = (
        orders["order_delivered_customer_date"] - orders["order_purchase_timestamp"]
    ).dt.total_seconds() / 86400  # dias
    orders["delivery_vs_estimate"] = (
        orders["order_delivered_customer_date"] - orders["order_estimated_delivery_date"]
    ).dt.total_seconds() / 86400  # dias (positivo = atrasado)
    orders["is_late"] = orders["delivery_vs_estimate"] > 0

    # Traduzir categorias
    products = dfs["products"].copy()
    cat_trans = dfs["category_translation"].copy()
    products = products.merge(cat_trans, on="product_category_name", how="left")
    products["category"] = products["product_category_name_english"].fillna(
        products["product_category_name"]
    )

    # Merge principal: orders + items + products + customers + sellers + payments + reviews
    order_items = dfs["order_items"].copy()
    payments = dfs["payments"].copy()
    reviews = dfs["reviews"].copy()
    customers = dfs["customers"].copy()
    sellers = dfs["sellers"].copy()

    # Reviews: pegar apenas a review mais recente por pedido
    reviews = reviews.sort_values("review_creation_date").drop_duplicates(
        subset=["order_id"], keep="last"
    )

    # Merge items com products
    items_products = order_items.merge(
        products[["product_id", "category", "product_category_name",
                  "product_weight_g", "product_length_cm",
                  "product_height_cm", "product_width_cm"]],
        on="product_id",
        how="left",
    )

    # Merge orders com customers
    orders_customers = orders.merge(
        customers[["customer_id", "customer_unique_id",
                   "customer_city", "customer_state"]],
        on="customer_id",
        how="left",
    )

    # DataFrame principal (nivel item)
    main_df = items_products.merge(orders_customers, on="order_id", how="left")
    main_df = main_df.merge(
        sellers[["seller_id", "seller_city", "seller_state"]],
        on="seller_id",
        how="left",
    )
    main_df = main_df.merge(
        reviews[["order_id", "review_score", "review_comment_message"]],
        on="order_id",
        how="left",
    )

    # Pagamentos agregados por pedido
    payments_agg = payments.groupby("order_id").agg(
        total_payment=("payment_value", "sum"),
        n_installments=("payment_installments", "max"),
        payment_types=("payment_type", lambda x: ", ".join(x.unique())),
        primary_payment=("payment_type", "first"),
    ).reset_index()

    main_df = main_df.merge(payments_agg, on="order_id", how="left")

    # Total por pedido (para analises a nivel pedido)
    order_totals = order_items.groupby("order_id").agg(
        total_items=("order_item_id", "count"),
        total_price=("price", "sum"),
        total_freight=("freight_value", "sum"),
    ).reset_index()
    order_totals["total_order_value"] = order_totals["total_price"] + order_totals["total_freight"]

    orders_full = orders_customers.merge(order_totals, on="order_id", how="left")
    orders_full = orders_full.merge(
        reviews[["order_id", "review_score", "review_comment_message"]],
        on="order_id",
        how="left",
    )
    orders_full = orders_full.merge(payments_agg, on="order_id", how="left")

    return {
        "main": main_df,
        "orders_full": orders_full,
        "orders": orders,
        "payments": payments,
        "reviews": reviews,
        "customers": customers,
        "sellers": sellers,
        "products": products,
        "geolocation": dfs["geolocation"],
    }