# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/127ai7gWu1ricucmFhP10XQkrBKRfBuBf
"""

"""
Expansoes do relatorio executivo Olist:
1. Contexto de mercado
2. Text mining de reviews
3. Previsao robusta com sazonalidade e cenarios
4. Analise de coorte
5. Recomendacoes com estimativas financeiras
"""

import os
import sys
import warnings
import re
from collections import Counter

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
import pandas as pd
import numpy as np

warnings.filterwarnings("ignore")

sns.set_theme(style="whitegrid", font_scale=1.1)
PALETTE = ["#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", "#9467bd",
           "#8c564b", "#e377c2", "#7f7f7f", "#bcbd22", "#17becf"]
plt.rcParams.update({
    "figure.facecolor": "white",
    "axes.facecolor": "white",
    "savefig.dpi": 150,
    "savefig.bbox": "tight",
    "font.family": "sans-serif",
})

CHARTS_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "output", "charts")
os.makedirs(CHARTS_DIR, exist_ok=True)

sys.path.insert(0, os.path.dirname(__file__))
from data_loader import load_all_datasets, clean_and_prepare  # noqa: E402


def save_fig(fig, name):
    path = os.path.join(CHARTS_DIR, name)
    fig.savefig(path, dpi=150, bbox_inches="tight", facecolor="white")
    plt.close(fig)
    print(f"  Salvo: {name}")


# ===========================================================================
# EXPANSAO 2: TEXT MINING DE REVIEWS
# ===========================================================================
def text_mining_reviews(data):
    print("\n=== EXPANSAO 2: TEXT MINING DE REVIEWS ===")
    reviews = data["orders_full"].copy()
    reviews = reviews.dropna(subset=["review_comment_message", "review_score"])

    # Stopwords em portugues (lista basica)
    stopwords_pt = {
        "a", "o", "e", "de", "da", "do", "em", "um", "uma", "que", "para", "com",
        "nao", "por", "mais", "se", "no", "na", "os", "as", "dos", "das", "ao",
        "mas", "ou", "foi", "tem", "ser", "eu", "me", "meu", "minha", "muito",
        "ja", "como", "sua", "seu", "ele", "ela", "nos", "esse", "essa", "isso",
        "este", "esta", "aqui", "ali", "la", "bem", "so", "ate", "pra", "tb",
        "ainda", "depois", "antes", "agora", "quando", "onde", "qual", "quem",
        "tudo", "nada", "cada", "mesmo", "outro", "outra", "outros", "outras",
        "voce", "vc", "estou", "esta", "estao", "vai", "vou", "pode", "ter",
        "tinha", "tive", "fiz", "fazer", "feito", "dia", "dias", "vez", "vezes",
        "sim", "tambem", "entao", "pois", "porque", "sobre", "entre", "sem",
        "pelo", "pela", "pelos", "pelas", "num", "numa", "nos", "das", "aos",
        "uns", "umas", "lhe", "lhes", "the", "and", "to", "of", "is", "it",
        "in", "for", "on", "with", "not", "are", "was", "were", "be", "have",
        "has", "had", "do", "does", "did", "will", "would", "could", "should",
        "all", "any", "some", "this", "that", "these", "those", "from", "they",
        "you", "we", "our", "your", "their", "its", "my", "his", "her",
    }

    def tokenize(text):
        text = str(text).lower()
        text = re.sub(r"[^a-záàâãéèêíïóôõúüç\s]", " ", text)
        words = text.split()
        return [w for w in words if len(w) > 2 and w not in stopwords_pt]

    # Separar reviews por score
    reviews_1 = reviews[reviews["review_score"] == 1]["review_comment_message"]
    reviews_5 = reviews[reviews["review_score"] == 5]["review_comment_message"]

    words_1 = Counter()
    for text in reviews_1:
        words_1.update(tokenize(text))

    words_5 = Counter()
    for text in reviews_5:
        words_5.update(tokenize(text))

    top_neg = words_1.most_common(20)
    top_pos = words_5.most_common(20)

    # --- Grafico: Top 20 palavras em reviews nota 1 vs nota 5 ---
    fig, axes = plt.subplots(1, 2, figsize=(16, 8))

    words_neg, counts_neg = zip(*top_neg)
    axes[0].barh(list(words_neg)[::-1], list(counts_neg)[::-1], color=PALETTE[3], edgecolor="white")
    axes[0].set_title("Top 20 Palavras - Reviews Nota 1\n(Insatisfeitos)", fontsize=13, fontweight="bold")
    axes[0].set_xlabel("Frequencia")

    words_pos, counts_pos = zip(*top_pos)
    axes[1].barh(list(words_pos)[::-1], list(counts_pos)[::-1], color=PALETTE[2], edgecolor="white")
    axes[1].set_title("Top 20 Palavras - Reviews Nota 5\n(Satisfeitos)", fontsize=13, fontweight="bold")
    axes[1].set_xlabel("Frequencia")

    fig.suptitle("Analise de Text Mining: O que Clientes Dizem?", fontsize=15, fontweight="bold", y=1.02)
    fig.tight_layout()
    save_fig(fig, "6_1_text_mining_reviews.png")

    # --- Temas recorrentes ---
    temas_negativos = {
        "atraso/entrega": ["entrega", "chegou", "atraso", "atrasado", "prazo", "demora",
                           "demorou", "demais", "dias", "esperando", "chegou"],
        "produto/qualidade": ["produto", "qualidade", "veio", "diferente", "quebrado",
                              "danificado", "defeito", "ruim"],
        "comunicacao": ["vendedor", "resposta", "contato", "informacao", "rastreamento",
                        "rastreio", "tracking"],
    }

    temas_positivos = {
        "entrega_rapida": ["rapido", "rapida", "antes", "prazo", "antecipado", "cedo"],
        "qualidade": ["otimo", "otima", "excelente", "perfeito", "perfeita", "qualidade",
                      "bom", "boa", "lindo", "linda", "bonito"],
        "recomendacao": ["recomendo", "amei", "adorei", "satisfeito", "satisfeita",
                         "parabens", "obrigado", "obrigada", "gostei"],
    }

    def count_theme(texts, keywords):
        count = 0
        for text in texts:
            text_lower = str(text).lower()
            if any(kw in text_lower for kw in keywords):
                count += 1
        return count

    reviews_1_list = reviews_1.tolist()
    reviews_5_list = reviews_5.tolist()

    tema_neg_counts = {tema: count_theme(reviews_1_list, kws) for tema, kws in temas_negativos.items()}
    tema_pos_counts = {tema: count_theme(reviews_5_list, kws) for tema, kws in temas_positivos.items()}

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    labels_neg = {"atraso/entrega": "Atraso/Entrega", "produto/qualidade": "Produto/Qualidade",
                  "comunicacao": "Comunicacao"}
    labels_pos = {"entrega_rapida": "Entrega Rapida", "qualidade": "Qualidade",
                  "recomendacao": "Recomendacao"}

    neg_labels = [labels_neg[k] for k in tema_neg_counts]
    neg_values = list(tema_neg_counts.values())
    neg_pcts = [v / len(reviews_1_list) * 100 for v in neg_values]
    axes[0].bar(neg_labels, neg_pcts, color=[PALETTE[3], PALETTE[1], PALETTE[4]], edgecolor="white")
    axes[0].set_ylabel("% das Reviews Nota 1")
    axes[0].set_title("Temas em Reviews Negativas", fontsize=12, fontweight="bold")
    for i, pct in enumerate(neg_pcts):
        axes[0].text(i, pct + 1, f"{pct:.1f}%", ha="center", fontsize=11, fontweight="bold")

    pos_labels = [labels_pos[k] for k in tema_pos_counts]
    pos_values = list(tema_pos_counts.values())
    pos_pcts = [v / len(reviews_5_list) * 100 for v in pos_values]
    axes[1].bar(pos_labels, pos_pcts, color=[PALETTE[2], PALETTE[0], PALETTE[4]], edgecolor="white")
    axes[1].set_ylabel("% das Reviews Nota 5")
    axes[1].set_title("Temas em Reviews Positivas", fontsize=12, fontweight="bold")
    for i, pct in enumerate(pos_pcts):
        axes[1].text(i, pct + 1, f"{pct:.1f}%", ha="center", fontsize=11, fontweight="bold")

    fig.suptitle("Temas Recorrentes nas Avaliacoes", fontsize=14, fontweight="bold", y=1.02)
    fig.tight_layout()
    save_fig(fig, "6_2_temas_reviews.png")

    total_com_comentario = len(reviews.dropna(subset=["review_comment_message"]))
    total_reviews = len(data["orders_full"].dropna(subset=["review_score"]))
    metricas = {
        "total_com_comentario": total_com_comentario,
        "total_reviews": total_reviews,
        "pct_com_comentario": total_com_comentario / total_reviews * 100,
        "tema_neg_principal": max(tema_neg_counts, key=tema_neg_counts.get),
        "tema_pos_principal": max(tema_pos_counts, key=tema_pos_counts.get),
    }
    print(f"  Reviews com comentario: {total_com_comentario:,} ({metricas['pct_com_comentario']:.1f}%)")
    print(f"  Tema negativo principal: {metricas['tema_neg_principal']}")
    print(f"  Tema positivo principal: {metricas['tema_pos_principal']}")
    return metricas


# ===========================================================================
# EXPANSAO 3: PREVISAO ROBUSTA COM SAZONALIDADE E CENARIOS
# ===========================================================================
def previsao_robusta(data):
    print("\n=== EXPANSAO 3: PREVISAO ROBUSTA ===")
    orders_full = data["orders_full"].copy()
    delivered = orders_full[
        orders_full["order_status"].isin(["delivered", "shipped", "invoiced", "processing"])
    ].dropna(subset=["order_purchase_timestamp"]).copy()

    delivered["year_month"] = delivered["order_purchase_timestamp"].dt.to_period("M")
    monthly = delivered.groupby("year_month").agg(
        receita=("total_order_value", "sum"),
        pedidos=("order_id", "nunique"),
    ).reset_index()
    monthly["month_num"] = range(len(monthly))
    monthly["year_month_str"] = monthly["year_month"].astype(str)

    # Remover primeiro e ultimo mes (possivelmente incompletos)
    if len(monthly) > 4:
        monthly_clean = monthly.iloc[1:-1].copy()
    else:
        monthly_clean = monthly.copy()

    # Media movel de 3 meses
    monthly_clean["receita_mm3"] = monthly_clean["receita"].rolling(window=3, center=True).mean()

    # Tendencia linear
    x = monthly_clean["month_num"].values
    y = monthly_clean["receita"].values
    coeffs = np.polyfit(x, y, 1)
    trend = np.poly1d(coeffs)

    # Calcular sazonalidade (razao entre valor real e tendencia)
    monthly_clean["trend_value"] = trend(monthly_clean["month_num"])
    monthly_clean["seasonal_ratio"] = monthly_clean["receita"] / monthly_clean["trend_value"]
    monthly_clean["month_of_year"] = monthly_clean["year_month"].apply(lambda x: x.month)
    seasonal_factors = monthly_clean.groupby("month_of_year")["seasonal_ratio"].mean()

    # Projecao 6 meses com sazonalidade
    last_month_num = monthly.iloc[-1]["month_num"]
    last_period = monthly.iloc[-1]["year_month"]

    future_data = []
    for i in range(1, 7):
        month_num = last_month_num + i
        period = last_period + i
        month_of_year = period.month
        base_value = trend(month_num)
        seasonal_factor = seasonal_factors.get(month_of_year, 1.0)
        projected = base_value * seasonal_factor
        future_data.append({
            "year_month_str": str(period),
            "month_num": month_num,
            "receita_base": base_value,
            "receita_projetada": projected,
            "seasonal_factor": seasonal_factor,
        })

    future_df = pd.DataFrame(future_data)

    # Cenarios
    std_residual = (monthly_clean["receita"] - monthly_clean["trend_value"]).std()
    future_df["cenario_otimista"] = future_df["receita_projetada"] * 1.15
    future_df["cenario_pessimista"] = future_df["receita_projetada"] * 0.85

    # --- Grafico: Previsao com cenarios ---
    fig, ax = plt.subplots(figsize=(16, 7))

    # Realizado
    ax.bar(range(len(monthly)), monthly["receita"] / 1000, color=PALETTE[0], alpha=0.7, label="Realizado")

    # Media movel
    mm3_idx = monthly_clean.index.tolist()
    ax.plot([i + 1 for i in range(len(monthly_clean))],
            monthly_clean["receita_mm3"].values / 1000,
            color=PALETTE[4], linewidth=2.5, linestyle="-", label="Media Movel 3M", marker="")

    # Projecao
    future_x = [len(monthly) + i for i in range(len(future_df))]
    ax.bar(future_x, future_df["receita_projetada"] / 1000, color=PALETTE[1], alpha=0.6,
           label="Projecao (com sazonalidade)")

    # Cenarios
    ax.fill_between(future_x,
                    future_df["cenario_pessimista"] / 1000,
                    future_df["cenario_otimista"] / 1000,
                    alpha=0.2, color=PALETTE[1], label="Intervalo Otimista/Pessimista (+/-15%)")

    # Linha de tendencia
    all_x = list(range(len(monthly) + len(future_df)))
    ax.plot(all_x, trend(all_x) / 1000, color=PALETTE[3], linestyle="--", linewidth=1.5,
            label="Tendencia Linear")

    all_labels = list(monthly["year_month_str"]) + list(future_df["year_month_str"])
    ax.set_xticks(range(0, len(all_labels), 2))
    ax.set_xticklabels([all_labels[i] for i in range(0, len(all_labels), 2)], rotation=45, ha="right")
    ax.set_xlabel("Mes")
    ax.set_ylabel("Receita (R$ mil)")
    ax.set_title("Previsao de Receita com Sazonalidade e Cenarios", fontsize=15, fontweight="bold")
    ax.legend(loc="upper left", fontsize=9)

    # Anotacao na area de projecao
    ax.axvline(x=len(monthly) - 0.5, color="gray", linestyle=":", alpha=0.7)
    ax.text(len(monthly) + 1, ax.get_ylim()[1] * 0.95, "PROJECAO", fontsize=11,
            color="gray", fontweight="bold", ha="center")

    fig.tight_layout()
    save_fig(fig, "7_1_previsao_cenarios.png")

    # --- Grafico: Fatores de sazonalidade ---
    fig, ax = plt.subplots(figsize=(10, 5))
    month_names = ["Jan", "Fev", "Mar", "Abr", "Mai", "Jun",
                   "Jul", "Ago", "Set", "Out", "Nov", "Dez"]
    available_months = sorted(seasonal_factors.index)
    labels = [month_names[m - 1] for m in available_months]
    values = [seasonal_factors[m] for m in available_months]
    colors_season = [PALETTE[2] if v >= 1 else PALETTE[3] for v in values]

    ax.bar(labels, values, color=colors_season, edgecolor="white")
    ax.axhline(y=1.0, color="gray", linestyle="--", alpha=0.7, label="Neutro (1.0)")
    ax.set_xlabel("Mes")
    ax.set_ylabel("Fator de Sazonalidade")
    ax.set_title("Fatores de Sazonalidade Mensal", fontsize=14, fontweight="bold")
    ax.legend()
    for i, v in enumerate(values):
        ax.text(i, v + 0.02, f"{v:.2f}", ha="center", fontsize=9)
    fig.tight_layout()
    save_fig(fig, "7_2_sazonalidade.png")

    receita_projetada_6m = future_df["receita_projetada"].sum()
    metricas = {
        "receita_projetada_6m": receita_projetada_6m,
        "crescimento_mensal_tendencia": coeffs[0],
        "cenario_otimista_6m": future_df["cenario_otimista"].sum(),
        "cenario_pessimista_6m": future_df["cenario_pessimista"].sum(),
    }
    print(f"  Receita projetada (6 meses): R$ {receita_projetada_6m:,.0f}")
    print(f"  Cenario otimista: R$ {metricas['cenario_otimista_6m']:,.0f}")
    print(f"  Cenario pessimista: R$ {metricas['cenario_pessimista_6m']:,.0f}")
    return metricas


# ===========================================================================
# EXPANSAO 4: ANALISE DE COORTE
# ===========================================================================
def analise_coorte(data):
    print("\n=== EXPANSAO 4: ANALISE DE COORTE ===")
    orders_full = data["orders_full"].copy()
    delivered = orders_full[orders_full["order_status"] == "delivered"].dropna(
        subset=["order_purchase_timestamp", "customer_unique_id"]
    ).copy()

    # Coorte = mes da primeira compra
    first_purchase = delivered.groupby("customer_unique_id")["order_purchase_timestamp"].min().reset_index()
    first_purchase.columns = ["customer_unique_id", "first_purchase"]
    first_purchase["cohort"] = first_purchase["first_purchase"].dt.to_period("M")

    delivered = delivered.merge(first_purchase, on="customer_unique_id", how="left")
    delivered["order_period"] = delivered["order_purchase_timestamp"].dt.to_period("M")
    delivered["cohort_month"] = (
        (delivered["order_period"] - delivered["cohort"]).apply(lambda x: x.n if hasattr(x, 'n') else 0)
    )

    # Tabela de coorte
    cohort_data = delivered.groupby(["cohort", "cohort_month"])["customer_unique_id"].nunique().reset_index()
    cohort_data.columns = ["cohort", "cohort_month", "customers"]

    cohort_pivot = cohort_data.pivot_table(
        index="cohort", columns="cohort_month", values="customers", fill_value=0
    )

    # Retencao relativa ao mes 0
    cohort_sizes = cohort_pivot[0]
    retention = cohort_pivot.divide(cohort_sizes, axis=0) * 100

    # Filtrar coortes com pelo menos 6 meses de dados e tamanho razoavel
    valid_cohorts = cohort_sizes[cohort_sizes >= 100].index
    retention_filtered = retention.loc[valid_cohorts]

    # Limitar a 12 meses
    max_months = min(12, retention_filtered.columns.max() + 1)
    retention_filtered = retention_filtered.iloc[:, :max_months]

    # Remover coortes com poucos meses de dados
    retention_filtered = retention_filtered.loc[
        retention_filtered.notna().sum(axis=1) >= 3
    ]

    # --- Grafico: Heatmap de retencao por coorte ---
    fig, ax = plt.subplots(figsize=(16, 10))
    labels = retention_filtered.copy()
    labels = labels.round(1)

    sns.heatmap(retention_filtered, annot=labels, fmt=".1f", cmap="YlOrRd",
                ax=ax, linewidths=0.5, cbar_kws={"label": "Taxa de Retencao (%)"},
                vmin=0, vmax=10)
    ax.set_xlabel("Meses desde Primeira Compra")
    ax.set_ylabel("Coorte (Mes da Primeira Compra)")
    ax.set_title("Analise de Retencao por Coorte", fontsize=15, fontweight="bold")
    yticklabels = [str(c) for c in retention_filtered.index]
    ax.set_yticklabels(yticklabels, rotation=0)
    fig.tight_layout()
    save_fig(fig, "8_1_cohort_retention.png")

    # --- Grafico: Curva de retencao media ---
    avg_retention = retention_filtered.mean()

    fig, ax = plt.subplots(figsize=(12, 5))
    ax.plot(avg_retention.index, avg_retention.values, color=PALETTE[0],
            marker="o", linewidth=2.5, markersize=8)
    ax.fill_between(avg_retention.index, avg_retention.values, alpha=0.15, color=PALETTE[0])
    ax.set_xlabel("Meses desde Primeira Compra")
    ax.set_ylabel("Taxa de Retencao Media (%)")
    ax.set_title("Curva de Retencao Media (todas as coortes)", fontsize=14, fontweight="bold")
    ax.set_xticks(avg_retention.index)
    for i, v in enumerate(avg_retention.values):
        if i <= 6 or i == len(avg_retention) - 1:
            ax.text(avg_retention.index[i], v + 0.2, f"{v:.1f}%", ha="center", fontsize=9)
    fig.tight_layout()
    save_fig(fig, "8_2_curva_retencao_media.png")

    # --- Grafico: Tamanho das coortes ---
    cohort_sizes_filtered = cohort_sizes.loc[valid_cohorts]

    fig, ax = plt.subplots(figsize=(14, 5))
    ax.bar(range(len(cohort_sizes_filtered)),
           cohort_sizes_filtered.values,
           color=PALETTE[0], edgecolor="white")
    ax.set_xticks(range(len(cohort_sizes_filtered)))
    ax.set_xticklabels([str(c) for c in cohort_sizes_filtered.index], rotation=45, ha="right")
    ax.set_xlabel("Coorte (Mes da Primeira Compra)")
    ax.set_ylabel("Novos Clientes")
    ax.set_title("Aquisicao de Novos Clientes por Coorte", fontsize=14, fontweight="bold")
    fig.tight_layout()
    save_fig(fig, "8_3_tamanho_coortes.png")

    ret_month1 = avg_retention.get(1, 0)
    ret_month3 = avg_retention.get(3, 0)
    ret_month6 = avg_retention.get(6, 0)
    metricas = {
        "retencao_mes1": ret_month1,
        "retencao_mes3": ret_month3,
        "retencao_mes6": ret_month6,
    }
    print(f"  Retencao media mes 1: {ret_month1:.2f}%")
    print(f"  Retencao media mes 3: {ret_month3:.2f}%")
    print(f"  Retencao media mes 6: {ret_month6:.2f}%")
    return metricas


# ===========================================================================
# EXPANSAO 5: RECOMENDACOES COM ESTIMATIVAS FINANCEIRAS
# ===========================================================================
def estimativas_financeiras(data, metricas_anteriores=None):
    print("\n=== EXPANSAO 5: ESTIMATIVAS FINANCEIRAS ===")
    orders_full = data["orders_full"].copy()
    delivered = orders_full[orders_full["order_status"] == "delivered"].dropna(
        subset=["total_order_value"])

    total_receita = delivered["total_order_value"].sum()
    total_clientes = delivered["customer_unique_id"].nunique()
    ticket_medio = delivered["total_order_value"].mean()
    total_pedidos = delivered["order_id"].nunique()

    customer_orders = delivered.groupby("customer_unique_id")["order_id"].nunique()
    clientes_recompra = (customer_orders > 1).sum()
    taxa_recompra_atual = clientes_recompra / total_clientes * 100

    # Cenario 1: Dobrar taxa de recompra (3% -> 6%)
    novos_recompra = int(total_clientes * 0.03)  # 3% adicionais
    receita_incremental_recompra = novos_recompra * ticket_medio
    pct_aumento_recompra = receita_incremental_recompra / total_receita * 100

    # Cenario 2: Reduzir atrasos em 50%
    atrasados = delivered[delivered["is_late"] == True]
    score_medio_atrasado = atrasados["review_score"].mean() if len(atrasados) > 0 else 3
    pedidos_atrasados = len(atrasados)
    pedidos_salvos = int(pedidos_atrasados * 0.5)

    # Cenario 3: Aumentar ticket medio em 10% via cross-sell
    receita_incremental_crosssell = total_receita * 0.10
    pct_aumento_crosssell = 10.0

    # Cenario 4: Reduzir frete em categorias criticas
    main = data["main"].copy()
    main_del = main[main["order_status"] == "delivered"].copy()
    cat_freight = main_del.groupby("category").agg(
        preco_medio=("price", "mean"),
        frete_medio=("freight_value", "mean"),
        count=("order_id", "count"),
        receita=("price", "sum"),
    )
    cat_freight["frete_pct"] = cat_freight["frete_medio"] / cat_freight["preco_medio"] * 100
    cats_alto_frete = cat_freight[cat_freight["frete_pct"] > 30]
    receita_cats_alto_frete = cats_alto_frete["receita"].sum()
    # Estimativa: reduzir frete em 20% nessas categorias aumenta conversao em 5%
    receita_incremental_frete = receita_cats_alto_frete * 0.05

    # --- Grafico: Impacto financeiro estimado por iniciativa ---
    initiatives = {
        "Programa de\nRecompra\n(3% -> 6%)": receita_incremental_recompra,
        "Cross-Sell\nInteligente\n(+10% ticket)": receita_incremental_crosssell,
        "Otimizacao\nde Frete\n(cats criticas)": receita_incremental_frete,
    }

    fig, ax = plt.subplots(figsize=(12, 6))
    names = list(initiatives.keys())
    values = [v / 1_000_000 for v in initiatives.values()]
    colors_init = [PALETTE[2], PALETTE[0], PALETTE[1]]

    bars = ax.bar(names, values, color=colors_init, edgecolor="white", width=0.6)
    ax.set_ylabel("Receita Incremental Estimada (R$ milhoes)")
    ax.set_title("Impacto Financeiro Estimado por Iniciativa Estrategica", fontsize=14, fontweight="bold")
    for bar, val in zip(bars, values):
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.02,
                f"R$ {val:.2f}M", ha="center", fontsize=12, fontweight="bold")
    ax.set_ylim(0, max(values) * 1.3)
    fig.tight_layout()
    save_fig(fig, "9_1_impacto_financeiro_iniciativas.png")

    # --- Grafico: Cenario de crescimento com iniciativas combinadas ---
    receita_total_incremental = sum(initiatives.values())
    receita_projetada_com_iniciativas = total_receita + receita_total_incremental

    fig, ax = plt.subplots(figsize=(10, 6))
    categories = ["Receita Atual\n(2016-2018)", "Com Recompra", "+ Cross-Sell", "+ Frete\n= PROJETADA"]
    cumulative = [
        total_receita,
        total_receita + receita_incremental_recompra,
        total_receita + receita_incremental_recompra + receita_incremental_crosssell,
        receita_projetada_com_iniciativas,
    ]
    cumulative_m = [v / 1_000_000 for v in cumulative]

    bars = ax.bar(categories, cumulative_m, color=[PALETTE[7], PALETTE[2], PALETTE[0], PALETTE[1]],
                  edgecolor="white", width=0.6)
    ax.set_ylabel("Receita (R$ milhoes)")
    ax.set_title("Receita Projetada com Iniciativas Estrategicas Combinadas",
                 fontsize=14, fontweight="bold")
    for bar, val in zip(bars, cumulative_m):
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.1,
                f"R$ {val:.1f}M", ha="center", fontsize=11, fontweight="bold")

    # Mostrar incremento
    aumento_pct = (receita_projetada_com_iniciativas - total_receita) / total_receita * 100
    ax.annotate(f"+{aumento_pct:.1f}%", xy=(3, cumulative_m[3]),
                xytext=(3, cumulative_m[3] + 0.8),
                fontsize=14, fontweight="bold", color=PALETTE[2],
                ha="center", va="bottom",
                arrowprops=dict(arrowstyle="->", color=PALETTE[2]))

    fig.tight_layout()
    save_fig(fig, "9_2_receita_com_iniciativas.png")

    metricas = {
        "receita_incremental_recompra": receita_incremental_recompra,
        "receita_incremental_crosssell": receita_incremental_crosssell,
        "receita_incremental_frete": receita_incremental_frete,
        "receita_total_incremental": receita_total_incremental,
        "aumento_pct": aumento_pct,
        "pedidos_salvos_logistica": pedidos_salvos,
    }
    print(f"  Receita incremental total: R$ {receita_total_incremental:,.0f}")
    print(f"  Aumento projetado: +{aumento_pct:.1f}%")
    return metricas


# ===========================================================================
# MAIN
# ===========================================================================
def main():
    print("=" * 60)
    print("EXPANSOES DO RELATORIO EXECUTIVO OLIST")
    print("=" * 60)

    print("\nCarregando datasets...")
    dfs = load_all_datasets()

    print("\nLimpando e preparando dados...")
    data = clean_and_prepare(dfs)

    m_text = text_mining_reviews(data)
    m_prev = previsao_robusta(data)
    m_coorte = analise_coorte(data)
    m_fin = estimativas_financeiras(data)

    print("\n" + "=" * 60)
    print("EXPANSOES CONCLUIDAS")
    print("=" * 60)
    print(f"  Novos graficos gerados: 7")
    print(f"  Total de graficos: 27")

    return {"text_mining": m_text, "previsao": m_prev, "coorte": m_coorte, "financeiro": m_fin}


if __name__ == "__main__":
    results = main()